# Generated by Django 6.1 on 2026-08-29 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='order_photos/original/')),
                ('filtered_image', models.ImageField(blank=True, null=True, upload_to='order_photos/filtered/')),
                ('shared_to_instagram', models.BooleanField(default=False)),
                ('admin_downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
