"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%07)^x%!7@t6e!7d8cx0t3&sv2&+)a)txux3%kz2mf^#pypd6p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] if DEBUG else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local apps
    'accounts',
    'menu',
    'orders',
    'rewards',
    'gallery',
    'wallet',
    'invoices',
    'dashboard',
    'pages',
]

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.admin_badges',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'accounts:login'

# ----- Persistent login -----
# User ko baar-baar login/OTP na karna pade — session 1 SAAL tak zinda rehta hai,
# browser band karne par bhi login state save rehti hai (jab tak user khud
# Logout na kare).
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 year
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
LOGIN_REDIRECT_URL = 'accounts:post_login_redirect'
LOGOUT_REDIRECT_URL = 'pages:home'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----- Wallet / Points -----
# Order place karne par turant koi points NAHI milte. Points sirf tab
# credit hote hain jab admin dashboard se order ka "Bill Paid" mark karta
# hai — dekho dashboard/views.py -> mark_bill_paid() aur
# SCRATCH_CARD_BONUS_POINTS (neeche) jitne points milte hain.

# ----- Invoice / GST settings -----
CGST_RATE = 2.5   # percent
SGST_RATE = 2.5   # percent
BUSINESS_NAME = "BOMBAY CHOWKK"
BUSINESS_TAGLINE = "BC SWAD HAI"
BUSINESS_ADDRESS = "123 MG Road, Thane, Maharashtra, India"
BUSINESS_GSTIN = "27ABCDE1234F1Z5"
BUSINESS_PHONE = "+91 98765 43210"
BUSINESS_WEBSITE = "https://bombaychowkk.in"
BUSINESS_FOOD_TAGLINE = "Pure Veg. Pure Taste."

# ----- Reward points per order -----
# Order place hote hi is amount ka "reward_points" us Order par fix ho jaata
# hai (Order.reward_points). Yeh points user ke WALLET me tabhi credit hote
# hain jab admin us order ka bill "Paid" mark karta hai — order place karte
# waqt NAHI milte.
SCRATCH_CARD_BONUS_POINTS = 40


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@rewardsapp.local'

# Production me console backend hataakar apna SMTP daalo, jaise:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'youremail@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
