# Generated by Django 6.1 on 2026-08-29 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nostalgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('story', models.TextField()),
            ],
            options={
                'db_table': 'nostalgia_pool',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.PositiveIntegerField(unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('reward', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reward_pool',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_expiry_days', models.PositiveIntegerField(default=60, help_text="Number of days after which an unrevealed scratch card will be marked as 'expired'.")),
            ],
            options={
                'db_table': 'site_config',
            },
        ),
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revealed', models.BooleanField(default=False)),
                ('reward_code', models.CharField(blank=True, max_length=100, null=True)),
                ('reward_label', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('nostalgia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.nostalgia')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_card', to='orders.order')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scratch_cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
